In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings('ignore') 

# sk learn import 
from sklearn.decomposition import PCA, KernelPCA
from sklearn.cross_validation import KFold, cross_val_score
from sklearn.metrics import make_scorer
from sklearn.grid_search import GridSearchCV
from sklearn.feature_selection import VarianceThreshold, RFE, SelectKBest, chi2
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier, ExtraTreesClassifier, GradientBoostingClassifier, VotingClassifier, RandomForestClassifier, AdaBoostClassifier

C:\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Anaconda3\lib\site-packages\sklearn\grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [2]:
train_1 = pd.read_csv(r"C:\Users\piush\Desktop\Dataset\AibHack\data\training.txt", sep="\t", encoding = 'iso-8859-1')
test_1 = pd.read_csv(r"C:\Users\piush\Desktop\Dataset\AibHack\data\testing.txt", sep="\t", encoding = 'iso-8859-1')

In [3]:
#Join the datasets
train = train_1.append(test_1,ignore_index = True)

In [4]:
train.loc[:, "SecSHFrac"] = train.loc[:, "SecSHFrac"].fillna(train['SecSHFrac'].median())
train.loc[:, "SecSHEfficiency"] = train.loc[:, "SecSHEfficiency"].fillna(train['SecSHEfficiency'].median())
train.loc[:, "MainWHEfficiency"] = train.loc[:, "MainWHEfficiency"].fillna(train['MainWHEfficiency'].median())
train.loc[:, "SecSHEfficiency"] = train.loc[:, "SecSHEfficiency"].fillna(train['SecSHEfficiency'].median())
train.loc[:, "SecSHFrac"] = train.loc[:, "SecSHFrac"].fillna(train['SecSHFrac'].median())
train.loc[:, "MainWHAdj"] = train.loc[:, "MainWHAdj"].fillna(train['MainWHAdj'].median())
train.loc[:, "SecSHFuel"] = train.loc[:, "SecSHFuel"].fillna(train['SecSHFuel'].median())
train.loc[:, "SecWHFuel"] = train.loc[:, "SecWHFuel"].fillna(train['SecWHFuel'].median())
train.loc[:, "SecSHFrac"] = train.loc[:, "SecSHFrac"].fillna(train['SecSHFrac'].median())
train.loc[:, "TempAdj"] = train.loc[:, "TempAdj"].fillna(train['TempAdj'].median())


In [5]:
train.loc[:, "FirstEnerType"] = train.loc[:, "FirstEnerType"].fillna("None")
train.loc[:, "FirstEnerTypeDescr"] = train.loc[:, "FirstEnerTypeDescr"].fillna("None")
train.loc[:, "FirstEnerType"] = train.loc[:, "FirstEnerType"].fillna("None")
train.loc[:, "FirstEnerTypeDescr"] = train.loc[:, "FirstEnerTypeDescr"].fillna("None")
train.loc[:, "FirstEnerType"] = train.loc[:, "FirstEnerType"].fillna("None")
train.loc[:, "FirstEnerTypeDescr"] = train.loc[:, "FirstEnerTypeDescr"].fillna("None")

train.loc[:, "PercLowEnergy"] = train.loc[:, "PercLowEnergy"].fillna("No")
train.loc[:, "ProdSecondEnerConvFac"] = train.loc[:, "ProdSecondEnerConvFac"].fillna("No")
train.loc[:, "ConsSecondEnerComment"] = train.loc[:, "ConsSecondEnerComment"].fillna("No")
train.loc[:, "SecondEnerTypeDescr"] = train.loc[:, "SecondEnerTypeDescr"].fillna("No")
train.loc[:, "ProdSecondEnerComment"] = train.loc[:, "ProdSecondEnerComment"].fillna("No")
train.loc[:, "ProdSecondEnerDelivered"] = train.loc[:, "ProdSecondEnerDelivered"].fillna("No")

#train.loc[:, "AvgWallU"] = train.loc[:, "AvgWallU"].fillna(0)
train.loc[:, "ProdFirstEnerComment"] = train.loc[:, "ProdFirstEnerComment"].fillna("No")
train.loc[:, "ProdFirstEnerDelivered"] = train.loc[:, "ProdFirstEnerDelivered"].fillna("No")
train.loc[:, "ProdFirstEnerConvFac"] = train.loc[:, "ProdFirstEnerConvFac"].fillna("No")
train.loc[:, "ConsFirstEnerComment"] = train.loc[:, "ConsFirstEnerComment"].fillna("No")
#train.loc[:, "MainSHEfficiency"] = train.loc[:, "MainSHEfficiency"].fillna("No")
train.loc[:, "PrimaryMainWaterEnergy"] = train.loc[:, "PrimaryMainWaterEnergy"].fillna(train['PrimaryMainWaterEnergy'].median())
train.loc[:, "PrimaryMainSpaceEnergy"] = train.loc[:, "PrimaryMainSpaceEnergy"].fillna(train['PrimaryMainSpaceEnergy'].median())
train.loc[:, "MainWaterCO2"] = train.loc[:, "MainWaterCO2"].fillna(train['MainWaterCO2'].median())
train.loc[:, "MainSpaceCO2"] = train.loc[:, "MainSpaceCO2"].fillna(train['MainSpaceCO2'].median())
train.loc[:, "SecSHFrac"] = train.loc[:, "SecSHFrac"].fillna(train['SecSHFrac'].median())
#train.loc[:, "PercLowEnergy"] = train.loc[:, "PercLowEnergy"].fillna(train['PercLowEnergy'].median())
#train.loc[:, "SecSpaceEnergy"] = train.loc[:, "SecSpaceEnergy"].fillna(train['SecSpaceEnergy'].median())
train.loc[:, "SecWaterEnergy"] = train.loc[:, "SecWaterEnergy"].fillna(train['SecWaterEnergy'].median())
train.loc[:, "SecSHFrac"] = train.loc[:, "SecSHFrac"].fillna(train['SecSHFrac'].median())
train.loc[:, "TempAdj"] = train.loc[:, "TempAdj"].fillna(train['TempAdj'].median())
train.loc[:, "TotPrimaryEnergyFac"] = train.loc[:, "TotPrimaryEnergyFac"].fillna(train['TotPrimaryEnergyFac'].median())

In [6]:
train.loc[:, "ConsThirdEnerComment"] = train.loc[:, "ConsThirdEnerComment"].fillna("No")
#train.loc[:, "ProdThirdEnerConvFac"] = train.loc[:, "ProdThirdEnerConvFac"].fillna("No")


train.loc[:, "SecSpaceEnergy"] = train.loc[:, "SecSpaceEnergy"].fillna("No")
train.loc[:, "ThirdEnerTypeDescr"] = train.loc[:, "ThirdEnerTypeDescr"].fillna("No")
train.loc[:, "ProdThirdEnerComment"] = train.loc[:, "ProdThirdEnerComment"].fillna("No")
train.loc[:, "ProdThirdEnerDelivered"] = train.loc[:, "ProdThirdEnerDelivered"].fillna("No")
train.loc[:, "ProdThirdEnerConvFac"] = train.loc[:, "ProdThirdEnerConvFac"].fillna("No")
#train.loc[:, "AvgWallU"] = train.loc[:, "AvgWallU"].fillna(0)
train.loc[:, "TotCO2Emissions"] = train.loc[:, "TotCO2Emissions"].fillna(train['TotCO2Emissions'].median())
train.loc[:, "PrimaryEnergySecondarySpace"] = train.loc[:, "PrimaryEnergySecondarySpace"].fillna(train['TotCO2Emissions'].median())

In [7]:
train.loc[:, "TotEnergy"] = train.loc[:, "TotEnergy"].fillna('No')
#train.loc[:, "TotEnergy"] = train.loc[:, "TotEnergy"].fillna(train['TotEnergy'].median())
train.loc[:, "SecSpaceCO2"] = train.loc[:, "SecSpaceCO2"].fillna(train['SecSpaceCO2'].median())

In [8]:
train.loc[:, "ConsThirdEnerComment"] = train.loc[:, "ConsThirdEnerComment"].fillna("No")
#train.loc[:, "ProdThirdEnerConvFac"] = train.loc[:, "ProdThirdEnerConvFac"].fillna("No")


train.loc[:, "SecSpaceEnergy"] = train.loc[:, "SecSpaceEnergy"].fillna("No")
train.loc[:, "ThirdEnerTypeDescr"] = train.loc[:, "ThirdEnerTypeDescr"].fillna("No")
train.loc[:, "ProdThirdEnerComment"] = train.loc[:, "ProdThirdEnerComment"].fillna("No")
train.loc[:, "ProdThirdEnerDelivered"] = train.loc[:, "ProdThirdEnerDelivered"].fillna("No")
train.loc[:, "ProdThirdEnerConvFac"] = train.loc[:, "ProdThirdEnerConvFac"].fillna("No")
#train.loc[:, "AvgWallU"] = train.loc[:, "AvgWallU"].fillna(0)
train.loc[:, "TotCO2Emissions"] = train.loc[:, "TotCO2Emissions"].fillna(train['TotCO2Emissions'].median())
train.loc[:, "PrimaryEnergySecondarySpace"] = train.loc[:, "PrimaryEnergySecondarySpace"].fillna(train['TotCO2Emissions'].median())

In [9]:
train.loc[:, "County"] = train.loc[:, "County"].fillna("None")
train.loc[:, "Type"] = train.loc[:, "Type"].fillna("None")
train.loc[:, "RatingType"] = train.loc[:, "RatingType"].fillna("None")
train.loc[:, "FirstEnerTypeDescr"] = train.loc[:, "FirstEnerTypeDescr"].fillna("None")
train.loc[:, "FirstEnerType"] = train.loc[:, "FirstEnerType"].fillna("None")
train.loc[:, "FirstEnerTypeDescr"] = train.loc[:, "FirstEnerTypeDescr"].fillna("None")

train.loc[:, "PercLowEnergy"] = train.loc[:, "PercLowEnergy"].fillna("No")
train.loc[:, "ProdSecondEnerConvFac"] = train.loc[:, "ProdSecondEnerConvFac"].fillna("No")
train.loc[:, "ConsSecondEnerComment"] = train.loc[:, "ConsSecondEnerComment"].fillna("No")
train.loc[:, "SecondEnerTypeDescr"] = train.loc[:, "SecondEnerTypeDescr"].fillna("No")
train.loc[:, "ProdSecondEnerComment"] = train.loc[:, "ProdSecondEnerComment"].fillna("No")
train.loc[:, "ProdSecondEnerDelivered"] = train.loc[:, "ProdSecondEnerDelivered"].fillna("No")

#train.loc[:, "AvgWallU"] = train.loc[:, "AvgWallU"].fillna(0)
train.loc[:, "ProdFirstEnerComment"] = train.loc[:, "ProdFirstEnerComment"].fillna("No")
train.loc[:, "ProdFirstEnerDelivered"] = train.loc[:, "ProdFirstEnerDelivered"].fillna("No")
train.loc[:, "ProdFirstEnerConvFac"] = train.loc[:, "ProdFirstEnerConvFac"].fillna("No")
train.loc[:, "ConsFirstEnerComment"] = train.loc[:, "ConsFirstEnerComment"].fillna("No")
#train.loc[:, "MainSHEfficiency"] = train.loc[:, "MainSHEfficiency"].fillna("No")
train.loc[:, "PrimaryMainWaterEnergy"] = train.loc[:, "PrimaryMainWaterEnergy"].fillna(train['PrimaryMainWaterEnergy'].median())
train.loc[:, "PrimaryMainSpaceEnergy"] = train.loc[:, "PrimaryMainSpaceEnergy"].fillna(train['PrimaryMainSpaceEnergy'].median())
train.loc[:, "MainWaterCO2"] = train.loc[:, "MainWaterCO2"].fillna(train['MainWaterCO2'].median())
train.loc[:, "MainSpaceCO2"] = train.loc[:, "MainSpaceCO2"].fillna(train['MainSpaceCO2'].median())
train.loc[:, "SecSHFrac"] = train.loc[:, "SecSHFrac"].fillna(train['SecSHFrac'].median())

In [10]:
#drop columns
del train['StorageLoss']
del train['DeclaredLoss']
del train['SolarWaterHeating']
del train['SummerElectricImm']
del train['Combi']
del train['KeepHot']
del train['VolWaterStorage']
del train['TempFac']
del train['TempFacMult']
del train['HWInsulationType']
del train['HWInsulationThickness']
del train['AreaAperture']
del train['ZeroLossCollEff']
del train['CollHeatLoss']

In [11]:
#drop columns 458880
del train['SolarRadiation']
del train['Overshading']
del train['DedicatedSolarVol']
del train['SolarPumpElect']
del train['SolarHeatFrac']
del train['LargestRoofTypeArea']
del train['LargestRoofType']
del train['SecSpacePrimaryEnergy']
del train['FuelTypeFirstBoiler']
del train['EffFirstHeatGenPlant']
del train['PercFirstHeat']
del train['FuelTypeSecondBoiler']
del train['FuelTypeThirdBoiler']
del train['EffThirdHeatGenPlant']
del train['PercThirdHeat']
del train['HeatingSystemSolarSpace']
#del train['TotPrimaryEnergyFac']

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
class_le = LabelEncoder()

In [22]:
train['County'] = class_le.fit_transform(train['County'].values)
train['Type'] = class_le.fit_transform(train['Type'].values)
train['RatingType'] = class_le.fit_transform(train['RatingType'].values)
#train['EnergyRatingCat'] = class_le.fit_transform(train['EnergyRatingCat'].values)
train['GroundFloorArea'] = class_le.fit_transform(train['GroundFloorArea'].values)
#train['MainSHFuel'] = class_le.fit_transform(train['MainSHFuel'].values)
#train['MainWHFuel'] = class_le.fit_transform(train['MainWHFuel'].values)
#train['SharedMPRN'] = class_le.fit_transform(train['SharedMPRN'].values)
#train['DLobby'] = class_le.fit_transform(train['DLobby'].values)
#train['VentMethod'] = class_le.fit_transform(train['VentMethod'].values)


In [24]:
#del train['MainWHFuel']
del train['SharedMPRN']
del train['DLobby']

In [34]:
train['Year'] = class_le.fit_transform(train['Year'].values)
#train['Charging'] = class_le.fit_transform(train['Charging'].values)
#train['MainSpaceEnergy'] = class_le.fit_transform(train['MainSpaceEnergy'].values)
#train['MassCat'] = class_le.fit_transform(train['MassCat'].values)
#train['TotEnergy'] = class_le.fit_transform(train['TotEnergy'].values)
#train['SecSpaceEnergy'] = class_le.fit_transform(train['SecSpaceEnergy'].values)
train['PercLivingArea'] = class_le.fit_transform(train['PercLivingArea'].values)
#train['RatingPurpose'] = class_le.fit_transform(train['RatingPurpose'].values)
#train['PrimaryLoss'] = class_le.fit_transform(train['PrimaryLoss'].values)
#train['DeclaredLoss'] = class_le.fit_transform(train['DeclaredLoss'].values)

TypeError: unorderable types: str() > float()

In [26]:
del train['Charging']

In [31]:
del train['MassCat']

In [33]:
del train['RatingPurpose']

In [46]:
#del train['PrimaryLoss']
#del train['AssessmentDate']
del train['ProdFirstEnerDelivered']
del train['ProdFirstEnerConvFac']
del train['ConsFirstEnerComment']
del train['ProdSecondEnerComment']

In [44]:
#train['AssessmentDate'] = class_le.fit_transform(train['AssessmentDate'].values)
#train['FirstEnerType'] = class_le.fit_transform(train['FirstEnerType'].values)
train['FirstEnerTypeDescr'] = class_le.fit_transform(train['FirstEnerTypeDescr'].values)
#train['ProdFirstEnerDelivered'] = class_le.fit_transform(train['ProdFirstEnerDelivered'].values)
train['ProdFirstEnerComment'] = class_le.fit_transform(train['ProdFirstEnerComment'].values)
#train['ProdFirstEnerConvFac'] = class_le.fit_transform(train['ProdFirstEnerConvFac'].values)
#train['ConsFirstEnerComment'] = class_le.fit_transform(train['ConsFirstEnerComment'].values)
train['SecondEnerTypeDescr'] = class_le.fit_transform(train['SecondEnerTypeDescr'].values)
#train['ProdSecondEnerComment'] = class_le.fit_transform(train['ProdSecondEnerComment'].values)
#train['DeclaredLoss'] = class_le.fit_transform(train['DeclaredLoss'].values)

In [48]:
del train['ProdSecondEnerDelivered']
del train['ProdSecondEnerConvFac']
del train['ConsSecondEnerComment']

In [50]:
#train['ProdSecondEnerDelivered'] = class_le.fit_transform(train['ProdSecondEnerDelivered'].values)
#train['ProdSecondEnerConvFac'] = class_le.fit_transform(train['ProdSecondEnerConvFac'].values)
#train['ConsSecondEnerComment'] = class_le.fit_transform(train['ConsSecondEnerComment'].values)
#train['MassCat'] = class_le.fit_transform(train['MassCat'].values)
train['ThirdEnerTypeDescr'] = class_le.fit_transform(train['ThirdEnerTypeDescr'].values)
#train['SecSpaceEnergy'] = class_le.fit_transform(train['SecSpaceEnergy'].values)
#train['ProdThirdEnerComment'] = class_le.fit_transform(train['ProdThirdEnerComment'].values)
#train['ProdThirdEnerDelivered'] = class_le.fit_transform(train['ProdThirdEnerDelivered'].values)
#train['ProdThirdEnerDelivered'] = class_le.fit_transform(train['ProdThirdEnerDelivered'].values)
#train['ConsThirdEnerComment'] = class_le.fit_transform(train['ConsThirdEnerComment'].values)

In [56]:
#del train['SecSpaceEnergy'] #= class_le.fit_transform(train['SecSpaceEnergy'].values)
#del train['ProdThirdEnerComment'] #= class_le.fit_transform(train['ProdThirdEnerComment'].values)
#del train['ProdThirdEnerDelivered'] #= class_le.fit_transform(train['ProdThirdEnerDelivered'].values)
#del train['ProdThirdEnerDelivered'] #= class_le.fit_transform(train['ProdThirdEnerDelivered'].values)
del train['ConsThirdEnerComment'] #= class_le.fit_transform(train['ConsThirdEnerComment'].values)

In [57]:
import re
missing_values = []
nonumeric_values = []

print ("TRAIN SET INFORMATION")
print ("========================\n")

for column in train:
    # Find all the unique feature values
    uniq = train[column].unique()
    print ("'{}' has {} unique values" .format(column,uniq.size))
    if (uniq.size > 17):
        print("~~Listing up to 17 unique values~~")
    print (uniq[0:17])
    print ("\n-----------------------------------------------------------------------\n")
    
    # Find features with missing values
    if (True in pd.isnull(uniq)):
        s = "{} has {} missing" .format(column, pd.isnull(train[column]).sum())
        missing_values.append(s)
    
    # Find features with non-numeric values
    for i in range (1, np.prod(uniq.shape)):
        if (re.match('nan', str(uniq[i]))):
            break
        if not (re.search('(^\d+\.?\d*$)|(^\d*\.?\d+$)', str(uniq[i]))):
            nonumeric_values.append(column)
            break
  
print ("\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n")
print ("Features with missing values:\n{}\n\n" .format(missing_values))
print ("Features with non-numeric values:\n{}" .format(nonumeric_values))
print ("\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n")

TRAIN SET INFORMATION

'BuildingID' has 623776 unique values
~~Listing up to 17 unique values~~
[190835 523113 271393 585961 624083  30231 350444 592196 365924 303002
 634938 300824 449623 379988  68299 597104 163298]

-----------------------------------------------------------------------

'County' has 56 unique values
~~Listing up to 17 unique values~~
[24  2  7  3 10 26  0 18  4 16  1 45  6 32 47 19 35]

-----------------------------------------------------------------------

'Type' has 12 unique values
[ 8  2 10  4  7  3 11  5  6  0  1  9]

-----------------------------------------------------------------------

'Year' has 253 unique values
~~Listing up to 17 unique values~~
[125 136 203 237 242 238 235 224 135 215 236 225 185 240 222 200 234]

-----------------------------------------------------------------------

'RatingType' has 4 unique values
[0 1 3 2]

-----------------------------------------------------------------------

'EnergyRatingCat' has 16 unique values
['F ' 'G ' '

In [73]:
import re
missing_values = []
nonumeric_values = []

print ("TRAIN SET INFORMATION")
print ("========================\n")

for column in train:
    # Find all the unique feature values
    uniq = train[column].unique()
    print ("'{}' has {} unique values" .format(column,uniq.size))
    if (uniq.size > 17):
        print("~~Listing up to 17 unique values~~")
    print (uniq[0:17])
    print ("\n-----------------------------------------------------------------------\n")
    
    # Find features with missing values
    if (True in pd.isnull(uniq)):
        s = "{} has {} missing" .format(column, pd.isnull(train[column]).sum())
        missing_values.append(s)
    
    # Find features with non-numeric values
    for i in range (1, np.prod(uniq.shape)):
        if (re.match('nan', str(uniq[i]))):
            break
        if not (re.search('(^\d+\.?\d*$)|(^\d*\.?\d+$)', str(uniq[i]))):
            nonumeric_values.append(column)
            break
  
print ("\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n")
print ("Features with missing values:\n{}\n\n" .format(missing_values))
print ("Features with non-numeric values:\n{}" .format(nonumeric_values))
print ("\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n")

TRAIN SET INFORMATION

'BuildingID' has 623776 unique values
~~Listing up to 17 unique values~~
[190835 523113 271393 585961 624083  30231 350444 592196 365924 303002
 634938 300824 449623 379988  68299 597104 163298]

-----------------------------------------------------------------------

'County' has 56 unique values
~~Listing up to 17 unique values~~
[24  2  7  3 10 26  0 18  4 16  1 45  6 32 47 19 35]

-----------------------------------------------------------------------

'Type' has 12 unique values
[ 8  2 10  4  7  3 11  5  6  0  1  9]

-----------------------------------------------------------------------

'Year' has 253 unique values
~~Listing up to 17 unique values~~
[125 136 203 237 242 238 235 224 135 215 236 225 185 240 222 200 234]

-----------------------------------------------------------------------

'RatingType' has 4 unique values
[0 1 3 2]

-----------------------------------------------------------------------

'EnergyRatingCat' has 16 unique values
['F ' 'G ' '

In [69]:
train.shape

(623776, 92)

In [59]:
target = train['EnergyRatingCat']

In [60]:
train_M = train[:train_1.shape[0]]
test = train[train_1.shape[0]:]

In [61]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100)

In [62]:
# Fit the model to our training data
clf = clf.fit(train_M, target)
score = clf.score(train_M, target)
"Mean accuracy of Random Forest: {0}".format(score)

ValueError: could not convert string to float: 'No'

In [66]:
del train_M['MainSHFuel']

In [64]:
train[['EnergyRatingCat', 'MainSHFuel', 'VentMethod', 'WallStructure', 'SuspWoodFloor', 'PermTest', 'TempAdj', 'BoilerStat1', 'BoilerStat2', 'OilPumpIn', 'WarmAir', 'Underfloor', 'CylinderThermostat', 'CombiCylinder', 'SolarPumpPower', 'MainWaterEnergy', 'MainSpaceEnergy', 'PrimaryMainWaterEnergy', 'PrimaryMainSpaceEnergy', 'MainWaterCO2', 'MainSpaceCO2', 'PercLowEnergy', 'TotEnergy', 'SecWaterEnergy', 'SecSpaceCO2', 'SecWaterCO2', 'SecWaterPrimaryEnergy', 'FirstEnerType', 'ProdThirdEnerConvFac', 'PrimaryEnergySecondarySpace', 'EnergyMainWater']]

EnergyRatingCat                      MainSHFuel     VentMethod  \
0                   F   Heating Oil                     Natural vent.   
1                   G   Heating Oil                     Natural vent.   
2                   D2  Heating Oil                     Natural vent.   
3                   C2  Mains Gas                       Natural vent.   
4                   B3  Mains Gas                       Natural vent.   
5                   B2  Mains Gas                       Natural vent.   
6                   C1  Mains Gas                       Natural vent.   
7                   E2  Solid Multi-Fuel                Natural vent.   
8                   D2  Heating Oil                     Natural vent.   
9                   C3  Mains Gas                       Natural vent.   
10                  G   Solid Multi-Fuel                Natural vent.   
11                  E1  Heating Oil                     Natural vent.   
12                  D1  Heating Oil                     Natural vent.   
13                  C1  Mains Gas                       Natural vent.   
14                  C2  Mains Gas                       Natural vent.   
15                  F   Heating Oil                     Natural vent.   
16                  C2  Mains Gas                       Natural vent.   
17                  F   Electricity                     Natural vent.   
18                  G   Electricity                     Natural vent.   
19                  C1  Heating Oil                     Natural vent.   
20                  B3  Mains Gas                       Natural vent.   
21                  E2  Heating Oil                     Natural vent.   
22                  D1  Mains Gas                       Natural vent.   
23                  D2  Heating Oil                     Natural vent.   
24                  C3  Heating Oil                     Natural vent.   
25                  C2  Mains Gas                       Natural vent.   
26                  B2  Bulk LPG (propane or butane)    Natural vent.   
27                  D1  Heating Oil                     Natural vent.   
28                  C3  Mains Gas                       Natural vent.   
29                  C3  Mains Gas                       Natural vent.   
...                ...                             ...            ...   
623746             NaN  Heating Oil                     Natural vent.   
623747             NaN  Mains Gas                       Natural vent.   
623748             NaN  Heating Oil                     Natural vent.   
623749             NaN  Heating Oil                     Natural vent.   
623750             NaN  Heating Oil                     Natural vent.   
623751             NaN  Electricity                     Natural vent.   
623752             NaN  Mains Gas                       Natural vent.   
623753             NaN  Heating Oil                     Natural vent.   
623754             NaN  Electricity                     Natural vent.   
623755             NaN  Mains Gas                       Natural vent.   
623756             NaN  Heating Oil                     Natural vent.   
623757             NaN  Mains Gas                       Natural vent.   
623758             NaN  Electricity                     Natural vent.   
623759             NaN  Heating Oil                     Natural vent.   
623760             NaN  Heating Oil                     Natural vent.   
623761             NaN  Heating Oil                     Natural vent.   
623762             NaN  Mains Gas                       Natural vent.   
623763             NaN  House Coal                      Natural vent.   
623764             NaN  Mains Gas                       Natural vent.   
623765             NaN  Electricity                     Natural vent.   
623766             NaN  Mains Gas                       Natural vent.   
623767             NaN  Heating Oil                     Natural vent.   
623768             NaN  Electricity                     Natural v